fix remarks Feature/groups
iostaf/DTAdmin pull request #14
Opened 2017-10-20 08:29 UTC by IvanKravchuk

2017-10-20 12:11 UTC, iostaf requested changes

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/Entities.swift
> +    init(groupId: String,groupName: String,facultyId: String,specialityId: String) {
Please put a space after commas

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/Entities.swift
> +    static func getGroupsFromJSON(json:[[String:String]]) -> [Group] {
Put a space after colons

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/Entities.swift
> +    static func getFacultiesFromJSON(json:[[String:String]]) -> [Faculty] {
Put a space after colons

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/Entities.swift
> +    static func getSpecialitiesFromJSON(json:[[String:String]]) -> [Speciality] {
Put a space after colons

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/Entities.swift
> +
Remove extra new lines

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/GroupViewController.swift
> +        getCommonArrayForGroups(){(result:[Group]) in
Put a space before and after a `{` and after a colon.

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/GroupViewController.swift
> +            (groupJSON:[[String:String]],groupResponce) in
Put spaces after colons and commas

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/GroupViewController.swift
> +                    (facultyJSON:[[String:String]],facultyResponce) in
Put spaces after colons, commas

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/GroupViewController.swift
> +                            (specialityJSON:[[String:String]],specialityResponce) in
Put spaces after colons, commas

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/HTTPService.swift
> +                completion(json!, response)
Do not use force unwrap Luke :)

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/LoginViewController.swift
> +                let groupViewController = storyBoard.instantiateViewController(withIdentifier: "GroupVC") as! GroupViewController
Use GroupViewController instead fo GroupVC. Having the same identifier and custom class makes a life easier

2017-10-20 12:11 UTC, iostaf commented on DTAdmin/LoginViewController.swift
> +                let storyBoard: UIStoryboard = UIStoryboard(name: "GroupSB", bundle: nil)
Use just Group instead fo GroupSB

2017-10-29 08:10 UTC, closed without merging

2026-09-02 14:00 UTC, dianapavaluc26 commented on DTAdmin/GroupViewController.swift
> +            (groupJSON:[[String:String]],groupResponce) in
Fixed in e4832b211. Assistant output persisted before response.created is now tracked and corrected after provider correlation, so the durable suppressHistoryReplay flag no longer depends on handler arrival order. Added a regression test that delivers transcript completion before response.created and verifies the persisted entry is repaired.