Feature/students & Data Manager Consolidate
iostaf/DTAdmin pull request #18
Opened 2017-10-27 10:07 UTC by winner23

The Pull request consists of three part:
1. Common DataManager for all entities 
2. The Entry-level structure for each entity (require testing and correction according to requirements)
3. Management of entity Student

2017-10-30 15:15 UTC, iostaf requested changes

2017-10-30 15:15 UTC, iostaf commented on DTAdmin.xcodeproj/project.pbxproj
> -    archiveVersion = 1;
I'm just curious, what have you done to produce such indentation mess in `project.pbxproj` file?

2017-10-30 15:15 UTC, iostaf commented on DTAdmin/MainTabBarController.swift
> +        let studentBarItem = UITabBarItem(title: "Students", image: nil, selectedImage: nil)
Please use NSLocalizedString for all user faced messages.

2017-10-30 15:15 UTC, iostaf commented on DTAdmin/Models/DataManager.swift
> +//  Created by Володимир on 10/24/17.
Please do not use Cyrillic characters.

2017-10-30 15:15 UTC, iostaf commented on DTAdmin/Models/DataManager.swift
> +    static var shared = DataManager()
Why not let instead of var?

2017-10-30 15:15 UTC, iostaf commented on DTAdmin/Student/Controllers/EditStudentViewController.swift
> +    func prepareForSave() -> Bool {
It's not clear what does this function do? When it returns true and when false?
Please write Swift doc for it

2017-10-30 15:15 UTC, iostaf commented on DTAdmin/Student/Controllers/EditStudentViewController.swift
> +    func convert(toSize size:CGSize, scale:CGFloat) -> UIImage
Why do we need this function? What does it do?

2017-10-30 15:15 UTC, iostaf commented on DTAdmin/Student/Controllers/GroupsTableViewController.swift
> +                self.showWarningMsg(error ?? "Incorect type data")
Please use NSLocalizedString for all user faced messages.

2017-10-30 15:15 UTC, iostaf commented on DTAdmin/Student/Controllers/StudentViewController.swift
> +                self.showWarningMsg(error ?? "Incorect type data")
Please use NSLocalizedString for all user faced messages.

2017-10-31 10:21 UTC, winner23 commented on DTAdmin.xcodeproj/project.pbxproj
> -    archiveVersion = 1;
I'm not sure that I made it manually...

2017-11-01 10:24 UTC, iostaf approved these changes

2017-11-01 10:24 UTC, merged