Feature/results reports
iostaf/DTAdmin pull request #38
Opened 2017-11-12 19:57 UTC by YuriiKrupa

2017-11-12 20:00 UTC, YuriiKrupa commented
![](https://github.trello.services/images/mini-trello-icon.png) [Results](https://trello.com/c/fOT1dZjp/25-results)

2017-11-14 08:24 UTC, iostaf requested changes

2017-11-14 08:24 UTC, iostaf commented on DTAdmin/Group/GroupDetailsViewController.swift
> +//      guard let test = tests?[indexPath.row] else {
Please remove commented dead code or provide good justification why have you commented it.

2017-11-14 08:24 UTC, iostaf commented on DTAdmin/Models/DataManager.swift
> +      if let error = error {
Please use 4 spaces for indentation

2017-11-14 08:24 UTC, iostaf commented on DTAdmin/Models/DataManager.swift
> +          if sessionResponse.statusCode == 200 {
Why do you use 200 here? AFAIK we have an enum for response codes.

2017-11-14 08:24 UTC, iostaf commented on DTAdmin/Models/Structures/ResultStructure.swift
> +struct ResultStructure: Serializable {
Please rename `ResultStructure` to something more meaningful and not use Structure suffix

2017-11-17 12:34 UTC, closed without merging